version: '3.8'

services:
  # Single-Cell Analysis Pipeline
  sc-analysis:
    build: .
    image: single-cell-analysis:latest
    container_name: sc-rna-seq-analysis
    volumes:
      - ./results:/app/results
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: "no"
